[workspace]
resolver = "2"
members = [
  "core",
  "crates/*",
  # "crates/p2p/tunnel",
  # "crates/p2p/tunnel/utils",
  "apps/cli",
  "apps/desktop/src-tauri",
  "apps/mobile/rust/*",
  "apps/server",
]

[workspace.dependencies]
prisma-client-rust =  { git = "https://github.com/Brendonovich/prisma-client-rust", rev = "c965b89f1a07a6931d90f4b5556421f7ffcda03b", features = [
  "rspc",
  "sqlite-create-many",
  "migrations",
  "sqlite",
], default-features = false }
prisma-client-rust-cli = { git = "https://github.com/Brendonovich/prisma-client-rust", rev = "c965b89f1a07a6931d90f4b5556421f7ffcda03b", features = [
  "rspc",
  "sqlite-create-many",
  "migrations",
  "sqlite",
], default-features = false }
prisma-client-rust-sdk = { git = "https://github.com/Brendonovich/prisma-client-rust", rev = "c965b89f1a07a6931d90f4b5556421f7ffcda03b", features = [
  "sqlite",
], default-features = false }

rspc = { version = "0.1.2" }
specta = { version = "0.0.6" }
httpz = { version = "0.0.3" }

swift-rs = { git = "https://github.com/Brendonovich/swift-rs.git", rev = "833e29ba333f1dfe303eaa21de78c4f8c5a3f2ff" }

tokio = { version = "1.25.0" }

[patch.crates-io]
openssl-sys = { git = "https://github.com/spacedriveapp/rust-openssl", rev = "66510ace8c803829a77f683d297179f7db2c7b6c" } # We use this patch so we can compile for the IOS simulator on M1
bip39 = { git = "https://github.com/spacedriveapp/rust-bip39", rev = "e9ee260fc6e35eb9bb2ad1c052185186f19a8ebe" } # Unpin `unicode-normalization` version (this increases MSRV but that is irrelevant for us)
tauri-build = { git = "https://github.com/tauri-apps/tauri", rev = "852e11e17b1573280671bfc4d5fae051aa218cf9" } # https://github.com/tauri-apps/tauri/issues/5070 (Fix will be release in v1.3)

rspc = { git = "https://github.com/oscartbeaumont/rspc", rev = "c03872c0ba29d2429e9c059dfb235cdd03e15e8c" }   # TODO: Move back to crates.io when new jsonrpc executor + `tokio::spawn` in the Tauri IPC plugin + upgraded Tauri & Axum version is released
specta = { git = "https://github.com/oscartbeaumont/rspc", rev = "c03872c0ba29d2429e9c059dfb235cdd03e15e8c" }
httpz = { git = "https://github.com/oscartbeaumont/httpz", rev = "a5185f2ed2fdefeb2f582dce38a692a1bf76d1d6" }