[package]
name = "spacedrive"
version = "0.1.0"
description = "The universal file manager."
authors = ["Spacedrive Technology Inc."]
license = ""
repository = "https://github.com/spacedriveapp/spacedrive"
default-run = "spacedrive"
edition = "2021"
build = "build.rs"

[dependencies]
tauri = { version = "1.2.4", features = ["api-all", "linux-protocol-headers", "macos-private-api"] }
rspc = { workspace = true, features = ["tauri"] }
httpz = { workspace = true, features = ["axum", "tauri"] } # TODO: The `axum` feature should be only enabled on Linux but this currently can't be done: https://github.com/rust-lang/cargo/issues/1197
sd-core = { path = "../../../core", features = ["ffmpeg", "location-watcher"] }
tokio = { workspace = true, features = ["sync"] }
window-shadows = "0.2.1"
tracing = "0.1.37"
serde = "1.0.152"
percent-encoding = "2.2.0"
http = "0.2.8"

[target.'cfg(target_os = "linux")'.dependencies]
server = { path = "../../server" }
axum = "0.6.6"
rand = "0.8.5"
url = "2.3.1"

[target.'cfg(target_os = "macos")'.dependencies]
swift-rs.workspace = true

[build-dependencies]
tauri-build = { version = "1.2.1", features = [] }

[target.'cfg(target_os = "macos")'.build-dependencies]
swift-rs = { workspace = true, features = ["build"] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
