[package]
name = "sd-core-mobile"
version = "0.1.0"
edition = "2021"
rust-version = "1.64.0"

[features]
android = ["sd-core/android"]

[dependencies]
once_cell = "1.17.0"
sd-core = { path = "../../../../core", features = [
  "mobile",
  "p2p",
], default-features = false }
rspc.workspace = true
serde_json = "1.0.93"
tokio = { workspace = true }
openssl = { version = "0.10.45", features = [
  "vendored",
] } # Override features of transitive dependencies
openssl-sys = { version = "0.9.80", features = [
  "vendored",
] } # Override features of transitive dependencies to support IOS Simulator on M1
futures = "0.3.26"
tracing = "0.1.37"
