[package]
name = "sd-sync-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.1.3"
once_cell = "1.17.0"
prisma-client-rust-sdk = { workspace = true }
proc-macro2 = "1.0.51"
quote = "1.0.23"
serde = { version = "1.0.152", features = ["derive"] }
thiserror = "1.0.38"
