[package]
name = "sd-p2p"
version = "0.1.0"
description = "Rust Peer to Peer Networking Library"
authors = ["Oscar Beaumont <oscar@otbeaumont.me>"]
edition = "2021"

[features]
default = []
serde = []
specta = []

[dependencies]
tokio = { workspace = true, features = ["macros", "sync", "time"] }
libp2p = { version = "0.51.0", features = ["tokio", "quic", "serde"] }
futures = "0.3.1"
mdns-sd = "0.6.1"
thiserror = "1.0.38"
tracing = "0.1.37"
serde = { version = "1.0.152", features = ["derive"] }
rmp-serde = "1.1.1"
smallvec = "1.10.0"
specta = { workspace = true }

[dev-dependencies]
tokio = {  workspace = true, features = ["rt-multi-thread"] }
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }

# TODO: This patch is done at the workspace level now
# [patch.crates-io]
# mdns-sd = { git = "https://github.com/oscartbeaumont/mdns-sd.git", rev = "45515a98e9e408c102871abaa5a9bff3bee0cbe8" }