[package]
name = "sd-p2p"
authors = ["Oscar Beaumont <oscar@otbeaumont.me>"]
version = "0.1.0"
edition = "2021"

[dependencies]
sd-tunnel-utils = { path = "./tunnel/utils" }

dashmap = "5.4.0"
rcgen = "0.9.3"
rustls = "0.20.8"
tokio = { workspace = true, features = ["macros", "sync"] }
if-watch = "1.1.1"
thiserror = "1.0.38"
mdns-sd = "0.5.10"
quinn = "0.8.5"
futures-util = "0.3.26"
ts-rs = "6.2.1"
serde = { version = "1.0.152", features = ["derive"] }
bip39 = { version = "1.0.1", features = ["rand"] }
rmp-serde = "1.1.1"
spake2 = "0.3.1"
ctrlc = { version = "3.2.5", features = ["termination"] }
tracing = "0.1.37"
specta = "0.0.2"

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread"] }
