[package]
name = "sd-crypto"
version = "0.0.0"
authors = ["Jake Robinson <jake@spacedrive.com>"]
readme = "README.md"
description = "A library to handle cryptographic functions within Spacedrive"
edition = "2021"
rust-version = "1.67.0"

[features]
rspc = ["dep:rspc"]
uuid = ["dep:uuid", "rspc?/uuid"]
serde = ["dep:serde", "dep:serde_json", "dep:serde-big-array", "uuid?/serde"]
encoding = ["dep:bincode"]
keymanager = ["dep:dashmap", "os-keyrings", "uuid", "async", "tokio?/sync"]
os-keyrings = ["dep:secret-service", "dep:security-framework"]
async = ["dep:tokio"]
examples = ["async", "tokio?/rt", "tokio?/macros"]

[dependencies]
# rng
rand = "0.8.5"
rand_chacha = "0.3.1"

# hashing
argon2 = "0.5.0"
balloon-hash = "0.4.0"
blake3 = { version = "1.3.3", features = ["traits-preview"] }

# ideally we want 2.5+ with `core_hint_black_box` and `const-generics` features
# but 2.4.x is pinned by one of our dependencies
subtle = { version = "2.4.1" }

# aeads
aes-gcm = "0.10.1"
chacha20poly1305 = "0.10.1"
aead = { version = "0.5.1", features = ["stream"] }

# cryptographic hygiene
zeroize = "1.5.7"

# error handling
thiserror = "1.0.37"

# header serialization
bincode = { version = "2.0.0-rc.2", optional = true }

# generic serialization
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
serde-big-array = { version = "0.5.1", optional = true }

# for storedkey organisation and handling
uuid = { version = "1.1.2", features = ["v4"], optional = true }

# better concurrency for the keymanager
dashmap = { version = "5.4.0", optional = true }

# optional, for support with rspc
rspc = { workspace = true, optional = true }

# for asynchronous crypto
tokio = { workspace = true, default-features = false, features = [
    "io-util",
    "rt-multi-thread",
], optional = true }

hex = "0.4.3"

# linux OS keyring - using `v2.0.2` as newer versions broke a lot due to async/lifetimes
[target.'cfg(target_os = "linux")'.dependencies]
secret-service = { version = "2.0.2", optional = true }

# macos/ios OS keyring
[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
security-framework = { version = "2.8.1", optional = true }

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "aes-256-gcm"
path = "benches/aes-256-gcm.rs"
harness = false

[[bench]]
name = "xchacha20-poly1305"
path = "benches/xchacha20-poly1305.rs"
harness = false

[[bench]]
name = "argon2id"
path = "benches/argon2id.rs"
harness = false

[[bench]]
name = "balloon-blake3"
path = "benches/balloon-blake3.rs"
harness = false

[[bench]]
name = "blake3-kdf"
path = "benches/blake3-kdf.rs"
harness = false

[[example]]
name = "single_file"
path = "examples/single_file.rs"
required-features = ["encoding", "examples"]

[[example]]
name = "single_file_with_metadata"
path = "examples/single_file_with_metadata.rs"
required-features = ["encoding", "examples"]

[[example]]
name = "single_file_with_preview_media"
path = "examples/single_file_with_preview_media.rs"
required-features = ["encoding", "examples"]
